import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import isMobile from "../utils/isMobile";
import dynamic from 'next/dynamic';

const Desktop = dynamic(()=> import('./Desktop'));
const Mobile = dynamic(()=> import('./Mobile'));

export default function Home({ isMobile }) {
console.log("sample", isMobile);
  return (
    <div className={styles.container}>
      <Head>
        <title>Noon.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { isMobile ? <Mobile /> : <Desktop />}
    </div>
  )
}

export async function getServerSideProps({ req }) {
  return {
    props: {
      isMobile: isMobile(req)
    }
  }
}
